apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nku76l91i-go 
  janus-idp.io/tekton: nku76l91i-go
  backstage.io/kubernetes-id: nku76l91i-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nku76l91i-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml